<a href="https://colab.research.google.com/github/hanidew/WIE3007-DMW-GroupProject/blob/main/DMW_GA2_Generate_Synthetic_Data_(Cleaned).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# ================================
# STEP 1: Install dependencies (UPDATED)
# ================================
!pip install -q torch torchvision torchaudio transformers accelerate bitsandbytes huggingface_hub pandas > /dev/null
!pip install -q ctgan  # <--- NEW: Install CTGAN
!pip install -q -U bitsandbytes # <--- FIX: Ensure latest bitsandbytes
print("✅ Dependencies installed.")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.4/74.4 kB 5.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 49.3 MB/s eta 0:00:00
✅ Dependencies installed.

In [2]:
# ================================
# STEP 2: Secure Login (FIXED)
# ================================
import os
from huggingface_hub import login
from google.colab import userdata

try:
    # This grabs the token from the "Key" icon on the left sidebar
    hf_token = userdata.get('HF_TOKEN')
    login(token=hf_token)
    print("✅ Logged in securely.")
except Exception as e:
    print("❌ Error: Could not find HF_TOKEN. Make sure you added it to the Secrets tab (Key icon)!")

# ================================
# STEP 3: Load Model (4-bit)
# ================================
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig, pipeline

# NEW:
model_name = "microsoft/Phi-3-mini-4k-instruct"

print("⏳ Loading model... (this takes 2-3 minutes)")

quant_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4"
)

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=quant_config,
    device_map="auto"
)

generator = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    device_map="auto"
)
print("✅ Model loaded.")

# ================================
# STEP 4: Prompt builder
# ================================
def build_prompt(n):
    return f"""[INST] Act as a Senior Risk Analyst and Synthetic Data Engine. Generate exactly {n} rows of realistic loan data.

FORMAT RULES (STRICT):
- One record per line
- Use | as delimiter
- No commas anywhere (especially in numbers like Annual_Income and Loan_Amount).
- No header row
- No explanations
- NO intro text like "Here are the records"
- NO conversational text.
- Raw text ONLY. Do NOT use markdown code blocks.

FIELDS ORDER:
Customer_ID|Age|Annual_Income|Credit_Score|Loan_Amount|Loan_Term_Months|Loan_Officer_Note|Default_Status

CONSTRAINTS (CRITICAL):
- Customer_ID: Format CUST-XXXX (e.g., CUST-0023), basically the format is like "CUST-" followed by 4 random digits.
- Age: 18–80
- Annual_Income: 20000–300000 (Integer only, NO commas, NEVER 0.)
- Credit_Score: 300–850 (Integer only)
- Loan_Amount: 5000–150000 (Integer only, NO commas)
- Loan_Term_Months: Choose standard terms (randomly choose from this selection): 12, 24, 36, 48, 60, or 72
- Default_Status: 0 (Good) or 1 (Default). Target 20% are 1.
- Loan_Officer_Note: 8-20 words. STRICTLY NO delimiter '|' inside.

LOGIC MAPPING (STRICT RELATIONSHIPS):
1. IF STATUS = 1 (DEFAULT):
   - Credit_Score MUST be between 300 and 600.
   - Loan_Officer_Note MUST use a Negative Trigger (e.g., "gambling", "lawsuit").
2. IF STATUS = 0 (GOOD):
   - Credit_Score MUST be between 650 and 850.
   - Loan_Officer_Note MUST use a Positive Trigger (e.g., "inheritance", "bonus") OR a Generic phrase.

NOTE GENERATION (Critical for Feature Extraction):
- Mix exactly ONE "Segment Hint" with ONE "Risk Context" per note.
- DO NOT start every sentence with "Client" or "Applicant". Vary the structure.
- STRICT RULE: Never use the words 'Default', 'Status', '1', or '0' inside the Loan_Officer_Note. Describe the behavior (e.g., 'unstable income') but never the result.

- SEGMENT HINTS (You MUST use one of these exact keywords to ensure classification and VARY these often):
   - Medical: "doctor", "nurse", "dentist", "pharmacist", "surgeon", "clinic"
   - Tech: "software engineer", "IT specialist", "developer", "cybersecurity", "programmer"
   - Education: "teacher", "professor", "tutor", "academic", "university"
   - Trade: "plumber", "mechanic", "electrician", "construction", "factory worker", "blue collar"
   - Service: "chef", "waiter", "artist", "designer", "retail", "driver"
   - Business: "manager", "consultant", "executive", "accountant", "sales rep", "broker"
   - Retired: "retiree", "pensioner", "elder"
   - Student: "student", "intern", "graduate"

- RISK CONTEXT (Must align with Status):
  - STATUS 1 (Default - Negative Triggers): "gambling losses", "lawsuit pending", "medical emergency costs", "unstable contracts", "over-leveraged assets", "declining revenue", "divorce settlement cost".
  - STATUS 0 (Good - POSITIVE ASSET TRIGGERS): You MUST randomly include one of these exact words for strong candidates: "inheritance", "bonus", "venture capital", "trust fund", "dividend", "royalty", "insurance settlement", "windfall".
  - STATUS 0 (Good - General): "steady cashflow", "strong savings", "low DTI", "early promotion".

ANOMALY & NOISE INSTRUCTIONS (CRITICAL FOR REALISM):
To challenge the ML model, 7% of these {n} rows must be 'Edge Cases':
1. THE UNEXPECTED DEFAULT: High Income (>100k) and High Credit (>750) but Status=1.
   Note must justify this (e.g., "Sudden medical emergency" or "Legal settlement").
2. THE UNEXPECTED GOOD PAYER: Low Income (<30k) and Low Credit (<550) but Status=0.
   Note must justify this (e.g., "Strong family guarantor" or "Asset-backed loan").
3. THE BORDERLINE CASE: Loan_Amount is exactly 2.5x Income. Make some 0 and some 1.

STRICT NUMERICAL CONSISTENCY:
Except for the 7% anomalies, ensure your logic is followed perfectly.

TWO PERFECT EXAMPLES (Follow this format):
CUST-9102|68|45000|710|120000|60|Client relies on fixed pension but loan amount is dangerously high for retirement budget|1
CUST-3321|29|92000|740|25000|24|Applicant has steady cashflow from tech stack job and low debt ratio|0

Generate {n} rows now. [/INST]
"""

✅ Logged in securely.
⏳ Loading model... (this takes 2-3 minutes)

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/306 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/599 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/967 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/2.67G [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.97G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/181 [00:00<?, ?B/s]

Device set to use cuda:0

✅ Model loaded.

In [4]:
# ================================
# STEP 5: Full Data Generation
# ================================
import csv
from tqdm import tqdm
import pandas as pd
import numpy as np

TARGET_ROWS = 1200
BATCH_SIZE = 50

header = [
    "Customer_ID", "Age", "Annual_Income", "Credit_Score",
    "Loan_Amount", "Loan_Term_Months", "Loan_Officer_Note",
    "Default_Status"
]

rows = []

print(f"🚀 Starting generation of {TARGET_ROWS} rows...")

# Initialize progress bar
pbar = tqdm(total=TARGET_ROWS, desc="Generating Rows")

while len(rows) < TARGET_ROWS:
    # 1. Ask Model for Data
    prompt = build_prompt(BATCH_SIZE)

    try:
        output = generator(
            prompt,
            max_new_tokens=2048,
            do_sample=True,
            temperature=0.7,
            top_p=0.9,
            repetition_penalty=1.1,
            return_full_text=False
        )

        # 2. Process Output
        lines = output[0]["generated_text"].strip().split("\n")

        for line in lines:
            values = [v.strip() for v in line.split("|")]

            # Validation: Must have exactly 8 columns
            if len(values) == len(header):
                rows.append(values)
                pbar.update(1)

                if len(rows) >= TARGET_ROWS:
                    break

    except Exception as e:
        print(f"⚠️ Minor error in batch: {e}")
        continue

pbar.close()
print(f"\n✅ Generation Complete! Total rows in memory: {len(rows)}")

# ================================
# STEP 6: SMART LOGIC ENFORCEMENT (Fixed & Connected)
# ================================
def enforce_business_logic(df):
    print("🔧 Running Python Logic Enforcement (With Gaussian Realism & Signal Booster)...")

    # Helper for realistic Gaussian numbers (clipped to bounds)
    def get_gaussian_scores(mean, std, low, high, size):
        vals = np.random.normal(mean, std, size)
        return np.clip(vals, low, high).astype(int)

    # ---------------------------------------------------------
    # 1. SANITIZE BASICS (Fix LLM Hallucinations)
    # ---------------------------------------------------------
    # Identify rows with invalid scores (0, or >850, or <300)
    mask_bad_score = (df['Credit_Score'] < 300) | (df['Credit_Score'] > 850)

    # Repair Defaults -> Gaussian around 520 (Bell curve)
    count_bad_def = (mask_bad_score & (df['Default_Status'] == 1)).sum()
    if count_bad_def > 0:
        df.loc[mask_bad_score & (df['Default_Status'] == 1), 'Credit_Score'] = \
            get_gaussian_scores(520, 50, 350, 580, count_bad_def)

    # Repair Good -> Gaussian around 720
    count_bad_good = (mask_bad_score & (df['Default_Status'] == 0)).sum()
    if count_bad_good > 0:
        df.loc[mask_bad_score & (df['Default_Status'] == 0), 'Credit_Score'] = \
            get_gaussian_scores(720, 50, 650, 820, count_bad_good)

    # Ensure Income is never 0 or too low (Gaussian around 45k for low end)
    mask_low_inc = df['Annual_Income'] < 10000
    if mask_low_inc.sum() > 0:
        df.loc[mask_low_inc, 'Annual_Income'] = \
            get_gaussian_scores(45000, 5000, 30000, 60000, mask_low_inc.sum())

    # ---------------------------------------------------------
    # 2. ENFORCE "ANOMALY" LOGIC (Varied Text Injection)
    # ---------------------------------------------------------

    # --- Anomaly A: Rich Defaulters ---
    candidates_rich = df[(df['Annual_Income'] > 100000) & (df['Credit_Score'] > 720)]
    if len(candidates_rich) > 0:
        # Target 20%
        idx_rich = candidates_rich.sample(frac=0.30, random_state=42).index
        df.loc[idx_rich, 'Default_Status'] = 1

        reasons = [
            " [Risk: Large gambling debt]", " [Risk: Pending lawsuit]",
            " [Risk: Speculative losses]", " [Risk: Hidden liabilities]",
            " [Risk: Divorce settlement]", " [Risk: Casino addiction]"
        ]
        random_reasons = np.random.choice(reasons, size=len(idx_rich))
        df.loc[idx_rich, 'Loan_Officer_Note'] = df.loc[idx_rich, 'Loan_Officer_Note'] + random_reasons

    # --- Anomaly B: Poor Good Payers ---
    candidates_poor = df[(df['Annual_Income'] < 40000) & (df['Credit_Score'] < 580)]
    if len(candidates_poor) > 0:
        idx_poor = candidates_poor.sample(frac=0.30, random_state=42).index
        df.loc[idx_poor, 'Default_Status'] = 0

        assets = [
            " [Asset: Family Guarantor]", " [Asset: Inheritance Trust]",
            " [Asset: Locked Savings]", " [Asset: Co-signer Verified]",
            " [Asset: Insurance Payout]"
        ]
        random_assets = np.random.choice(assets, size=len(idx_poor))
        df.loc[idx_poor, 'Loan_Officer_Note'] = df.loc[idx_poor, 'Loan_Officer_Note'] + random_assets

    # ---------------------------------------------------------
    # 3. ENFORCE "BORDERLINE" LOGIC (Math Check)
    # ---------------------------------------------------------
    # "Standard" Over-leveraged people (High DTI) should default
    df['DTI_Ratio'] = df['Loan_Amount'] / df['Annual_Income']

    # Filter: High DTI + Good Status + NO Asset keywords
    mask_risk = (df['DTI_Ratio'] > 2.5) & \
                (df['Default_Status'] == 0) & \
                (~df['Loan_Officer_Note'].str.contains("Guarantor|Inheritance|Asset|Co-signer", case=False, na=False))

    df.loc[mask_risk, 'Default_Status'] = 1
    df.drop(columns=['DTI_Ratio'], inplace=True)

    # ---------------------------------------------------------
    # 4. SIGNAL BOOSTER (90% Rule)
    # ---------------------------------------------------------
    # Find Defaulters who MIGHT be missing a negative keyword
    risk_keywords = "gambling|lawsuit|medical|unstable|over-leveraged|declining|divorce|risk|debt"
    weak_defaulters = (df['Default_Status'] == 1) & (~df['Loan_Officer_Note'].str.contains(risk_keywords, case=False))

    # Force inject risk phrase into MOST (but not all) weak defaulters
    if weak_defaulters.sum() > 0:
        weak_indices = df[weak_defaulters].index

        # Select 90% to fix (Leave 10% as "Mystery Defaults" to challenge the model)
        # This prevents the model from relying ONLY on text
        indices_to_fix = np.random.choice(weak_indices, size=int(len(weak_indices) * 0.7), replace=False)

        extra_risks = [
            " [Note: History of late payments]",
            " [Note: High debt-to-income]",
            " [Note: erratic cash flow]"
        ]

        if len(indices_to_fix) > 0:
            df.loc[indices_to_fix, 'Loan_Officer_Note'] = df.loc[indices_to_fix, 'Loan_Officer_Note'] + np.random.choice(extra_risks, size=len(indices_to_fix))
            print(f"✅ Signal Booster applied to {len(indices_to_fix)} rows (leaving some mysteries).")

    print("✅ Logic Enforcement Complete. Data is clean, varied, and realistic.")
    return df

# ================================
# THE BRIDGE: Prepare Data & Apply Logic
# ================================
# 1. Create Raw DataFrame from list
df_raw = pd.DataFrame(rows[:TARGET_ROWS], columns=header)

# 2. Convert Columns to Numeric (Essential for the logic to work!)
num_cols = ["Age", "Annual_Income", "Credit_Score", "Loan_Amount", "Loan_Term_Months", "Default_Status"]
for col in num_cols:
    df_raw[col] = pd.to_numeric(df_raw[col], errors='coerce')

# 3. Drop rows where numeric conversion failed (NaNs)
df_raw.dropna(subset=num_cols, inplace=True)

# 4. CALL THE FUNCTION (The critical step!)
df_final = enforce_business_logic(df_raw)

# ================================
# STEP 7: Save RAW Dataset
# ================================
output_file = "synthetic_financial_data_FINAL.csv"
df_final.to_csv(output_file, sep='|', index=False, header=True)
print(f"\n💾 File saved successfully: {output_file}")

# ================================
# STEP 8: Verify Dataset
# ================================
try:
    df_verify = pd.read_csv(output_file, sep='|')
    print("\n📊 DATASET SUMMARY:")
    print(f"Shape: {df_verify.shape}")
    print("-" * 30)
    print(df_verify.head())
    print("-" * 30)
    print("\n🔍 Checking Class Balance:")
    print(df_verify['Default_Status'].value_counts(normalize=True))

    print("\n🔍 Checking Score Integrity (Should be 300-850):")
    print(f"Min: {df_verify['Credit_Score'].min()}, Max: {df_verify['Credit_Score'].max()}")

    # Quick Correlation Check
    corr = df_verify['Credit_Score'].corr(df_verify['Default_Status'])
    print(f"\n🔍 Correlation (Score vs Default): {corr:.4f} (Should be negative)")

except Exception as e:
    print("❌ Error reading CSV:", e)

🚀 Starting generation of 1200 rows...

Generating Rows:   6%|▌         | 69/1200 [44:09<12:03:43, 38.39s/it]

Generating Rows:   0%|          | 1/1200 [01:18<26:09:33, 78.54s/it]
Generating Rows:   2%|▏         | 24/1200 [02:04<1:23:16,  4.25s/it]
Generating Rows:   3%|▎         | 36/1200 [02:29<1:05:00,  3.35s/it]
Generating Rows:   3%|▎         | 41/1200 [03:57<1:59:23,  6.18s/it]
Generating Rows:   4%|▍         | 51/1200 [06:06<2:45:04,  8.62s/it]You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

Generating Rows:   7%|▋         | 79/1200 [08:07<1:53:37,  6.08s/it]
Generating Rows:   7%|▋         | 80/1200 [10:11<2:58:20,  9.55s/it]
Generating Rows:  10%|▉         | 118/1200 [11:20<1:26:33,  4.80s/it]
Generating Rows:  11%|█▏        | 136/1200 [11:42<1:06:28,  3.75s/it]
Generating Rows:  12%|█▏        | 141/1200 [13:42<1:43:10,  5.85s/it]
Generating Rows:  15%|█▍        | 176/1200 [14:10<55:58,  3.28s/it]
Generating Rows:  15%|█▌        | 182/1200 [16:19<1:29:47,  5.29s/it]
Generating Rows:  17%|█▋        | 199/1200 [16:52<1:10:57,  4.25s/it]
Generating Rows:  17%|█▋        | 208/1200 [18:58<1:41:15,  6.12s/it]
Generating Rows:  18%|█▊        | 219/1200 [21:06<2:02:23,  7.49s/it]
Generating Rows:  21%|██▏       | 255/1200 [23:13<1:24:23,  5.36s/it]
Generating Rows:  21%|██▏       | 257/1200 [24:24<1:43:39,  6.60s/it]
Generating Rows:  22%|██▏       | 259/1200 [25:55<2:16:51,  8.73s/it]
Generating Rows:  24%|██▎       | 284/1200 [27:44<1:40:11,  6.56s/it]
Generating Rows:  26%|██▌       | 313/1200 [29:51<1:22:34,  5.59s/it]
Generating Rows:  28%|██▊       | 341/1200 [30:29<56:41,  3.96s/it]
Generating Rows:  29%|██▉       | 346/1200 [31:10<1:01:41,  4.33s/it]
Generating Rows:  30%|██▉       | 354/1200 [32:42<1:18:12,  5.55s/it]
Generating Rows:  32%|███▏      | 379/1200 [34:40<1:11:03,  5.19s/it]
Generating Rows:  34%|███▍      | 413/1200 [36:47<59:28,  4.53s/it]
Generating Rows:  36%|███▌      | 429/1200 [38:57<1:09:05,  5.38s/it]
Generating Rows:  36%|███▌      | 430/1200 [41:05<1:41:10,  7.88s/it]
Generating Rows:  38%|███▊      | 456/1200 [41:39<1:02:30,  5.04s/it]
Generating Rows:  38%|███▊      | 461/1200 [42:12<1:04:07,  5.21s/it]
Generating Rows:  39%|███▉      | 467/1200 [44:01<1:27:56,  7.20s/it]
Generating Rows:  42%|████▏     | 500/1200 [44:44<46:15,  3.97s/it]
Generating Rows:  42%|████▎     | 510/1200 [45:42<49:45,  4.33s/it]
Generating Rows:  44%|████▍     | 527/1200 [47:44<58:42,  5.23s/it]
Generating Rows:  47%|████▋     | 561/1200 [49:40<46:26,  4.36s/it]
Generating Rows:  50%|████▉     | 594/1200 [50:26<32:08,  3.18s/it]
Generating Rows:  50%|█████     | 603/1200 [52:33<46:14,  4.65s/it]
Generating Rows:  51%|█████     | 608/1200 [54:40<1:05:34,  6.65s/it]
Generating Rows:  53%|█████▎    | 640/1200 [55:45<41:50,  4.48s/it]
Generating Rows:  55%|█████▍    | 654/1200 [57:51<50:11,  5.52s/it]
Generating Rows:  58%|█████▊    | 692/1200 [58:13<27:05,  3.20s/it]
Generating Rows:  58%|█████▊    | 693/1200 [1:00:02<42:29,  5.03s/it]
Generating Rows:  60%|██████    | 720/1200 [1:02:36<42:22,  5.30s/it]
Generating Rows:  60%|██████    | 725/1200 [1:04:42<57:00,  7.20s/it]
Generating Rows:  64%|██████▎   | 762/1200 [1:07:46<44:22,  6.08s/it]
Generating Rows:  66%|██████▋   | 797/1200 [1:08:05<25:49,  3.84s/it]
Generating Rows:  67%|██████▋   | 800/1200 [1:09:08<31:03,  4.66s/it]
Generating Rows:  68%|██████▊   | 813/1200 [1:09:48<27:43,  4.30s/it]
Generating Rows:  69%|██████▊   | 823/1200 [1:10:54<29:50,  4.75s/it]
Generating Rows:  70%|███████   | 842/1200 [1:12:53<31:33,  5.29s/it]
Generating Rows:  73%|███████▎  | 877/1200 [1:14:58<23:59,  4.46s/it]
Generating Rows:  76%|███████▌  | 910/1200 [1:15:56<16:25,  3.40s/it]
Generating Rows:  77%|███████▋  | 921/1200 [1:17:16<18:39,  4.01s/it]
Generating Rows:  78%|███████▊  | 941/1200 [1:19:02<18:54,  4.38s/it]
Generating Rows:  81%|████████  | 968/1200 [1:19:35<12:34,  3.25s/it]
Generating Rows:  82%|████████▏ | 979/1200 [1:22:13<19:03,  5.18s/it]
Generating Rows:  84%|████████▍ | 1010/1200 [1:24:18<14:54,  4.71s/it]
Generating Rows:  87%|████████▋ | 1039/1200 [1:26:11<11:51,  4.42s/it]
Generating Rows:  89%|████████▉ | 1068/1200 [1:28:14<09:35,  4.36s/it]
Generating Rows:  92%|█████████▏| 1108/1200 [1:29:30<05:11,  3.38s/it]
Generating Rows:  93%|█████████▎| 1112/1200 [1:31:20<06:50,  4.67s/it]
Generating Rows:  95%|█████████▌| 1141/1200 [1:33:24<04:27,  4.53s/it]
Generating Rows:  97%|█████████▋| 1169/1200 [1:34:11<01:51,  3.59s/it]
Generating Rows: 100%|██████████| 1200/1200 [1:36:17<00:00,  4.81s/it]

✅ Generation Complete! Total rows in memory: 1200
🔧 Running Python Logic Enforcement (With Gaussian Realism & Signal Booster)...
✅ Signal Booster applied to 217 rows (leaving some mysteries).
✅ Logic Enforcement Complete. Data is clean, varied, and realistic.

💾 File saved successfully: synthetic_financial_data_FINAL.csv

📊 DATASET SUMMARY:
Shape: (1091, 8)
------------------------------
  Customer_ID   Age  Annual_Income  Credit_Score  Loan_Amount  \
0   CUST-4321  55.0       120000.0         770.0     160000.0
1   CUST-2056  40.0       150000.0         780.0      90000.0
2   CUST-9812  34.0        75000.0         660.0     110000.0
3   CUST-8132  28.0        32000.0         710.0      60000.0
4   CUST-0543  45.0        80000.0         820.0     240000.0

   Loan_Term_Months                                  Loan_Officer_Note  \
0              48.0  Teaching assistant facing sudden hospital bill...
1              36.0  Photographer inherits art collection easing fi...
2              48.0  Retail store owner deals daily challenges due ...
3              24.0  Software developer secures bonus which helps c...
4              72.0  Business consultant recently benefited from su...

   Default_Status
0             1.0
1             0.0
2             1.0
3             0.0
4             1.0
------------------------------

🔍 Checking Class Balance:
Default_Status
0.0    0.577452
1.0    0.422548
Name: proportion, dtype: float64

🔍 Checking Score Integrity (Should be 300-850):
Min: 450.0, Max: 850.0

🔍 Correlation (Score vs Default): 0.0281 (Should be negative)

# Clean Dataset

In [5]:
import pandas as pd

# 1. Load the raw file
df = pd.read_csv('synthetic_financial_data_FINAL.csv', sep='|')

# 2. Fix the Customer IDs (Standardize to 'CUST-XXXX')
# This replaces any underscore '_' with a hyphen '-'
df['Customer_ID'] = df['Customer_ID'].str.replace('_', '-', regex=False)

# 3. Convert Floats to Integers
# We explicitly convert these columns to 'int64' to remove the ".0"
cols_to_fix = ["Age", "Annual_Income", "Credit_Score", "Loan_Amount", "Loan_Term_Months", "Default_Status"]
for col in cols_to_fix:
    df[col] = df[col].astype(int)

# 4. Save the "Gold Standard" version
df.to_csv('synthetic_financial_data_CLEAN.csv', sep='|', index=False)

print("✨ Dataset Polished!")
print(df.head())
print(f"\nVerifying IDs: {df['Customer_ID'].str.contains('_').sum()} underscores remaining (Should be 0).")

✨ Dataset Polished!
  Customer_ID  Age  Annual_Income  Credit_Score  Loan_Amount  \
0   CUST-4321   55         120000           770       160000
1   CUST-2056   40         150000           780        90000
2   CUST-9812   34          75000           660       110000
3   CUST-8132   28          32000           710        60000
4   CUST-0543   45          80000           820       240000

   Loan_Term_Months                                  Loan_Officer_Note  \
0                48  Teaching assistant facing sudden hospital bill...
1                36  Photographer inherits art collection easing fi...
2                48  Retail store owner deals daily challenges due ...
3                24  Software developer secures bonus which helps c...
4                72  Business consultant recently benefited from su...

   Default_Status
0               1
1               0
2               1
3               0
4               1

Verifying IDs: 0 underscores remaining (Should be 0).

# Feature Engineering

CPU version

In [7]:
import pandas as pd
import numpy as np
import re
from tqdm import tqdm
from google.colab import drive

# ---------------------------------------------------------
# 0. SETUP
# ---------------------------------------------------------
# drive.mount('/content/drive')  # Uncomment if using Drive
file_path = 'synthetic_financial_data_CLEAN.csv'  # Using the clean version

try:
    df = pd.read_csv(file_path, sep='|')
    print(f"✅ Loaded {len(df)} rows.")
except FileNotFoundError:
    print("❌ File not found. Make sure you ran the 'Cleaning' step!")

# ---------------------------------------------------------
# 1. DEFINE EXTRACTION LOGIC (Matched to Generator)
# ---------------------------------------------------------
def extract_features(row):
    note = str(row['Loan_Officer_Note']).lower()

    # --- A. OCCUPATION (Matched to Prompt Keywords) ---
    # We refined these to match the specific words the LLM was told to use
    # --- UPDATED OCCUPATION LOGIC (Catches ~90% of jobs) ---
    jobs = {
        'Medical':   r'\b(doctor|nurse|dentist|pharmacist|surgeon|clinic|practitioner|medical)\b',
        'Tech':      r'\b(software|developer|it specialist|cybersecurity|programmer|tech|data|engineer)\b',
        'Education': r'\b(teacher|professor|tutor|academic|university|teaching|faculty)\b',
        'Trade':     r'\b(plumber|mechanic|electrician|construction|factory|blue collar|technician|driver)\b',
        'Service':   r'\b(chef|waiter|waitress|artist|designer|retail|clerk|staff|customer|service)\b',
        'Business':  r'\b(manager|consultant|executive|accountant|sales|broker|business|owner|professional|founder|entrepreneur)\b',
        'Real Estate': r'\b(estate|agent|realtor|property|landlord)\b',  # NEW CATEGORY
        'Retired':   r'\b(retiree|pension|elder|retired)\b',
        'Student':   r'\b(student|intern|graduate)\b'
    }

    found_job = "Other"
    for category, pattern in jobs.items():
        if re.search(pattern, note):
            found_job = category
            break

    # --- B. POSITIVE ASSETS (The "Good" Signal) ---
    # Keywords: inheritance, bonus, venture, trust, dividend, royalty, insurance, windfall
    asset_pattern = r'\b(inheritance|bonus|venture|trust|dividend|royalty|insurance|windfall)\b'
    has_asset = 1 if re.search(asset_pattern, note) else 0

    # --- C. NEGATIVE RISKS (The "Bad" Signal - NEW!) ---
    # Keywords: gambling, lawsuit, medical emergency, unstable, over-leveraged, divorce, late payment
    # This is crucial because of the "Signal Booster" we ran earlier.
    risk_pattern = r'\b(gambling|lawsuit|medical|unstable|over-leveraged|declining|divorce|late payment|erratic|debt)\b'
    risk_flag = 1 if re.search(risk_pattern, note) else 0

    return pd.Series([found_job, has_asset, risk_flag])

# ---------------------------------------------------------
# 2. RUN EXTRACTION
# ---------------------------------------------------------
print("🚀 Running Smart Feature Extraction...")
tqdm.pandas()

# Apply the text mining
df[['Occupation', 'Has_Asset', 'Risk_Flag']] = df.progress_apply(extract_features, axis=1)

# ---------------------------------------------------------
# 3. ADD MATHEMATICAL FEATURES (The "DTI" Rule)
# ---------------------------------------------------------
print("🧮 Calculating Financial Ratios...")

# DTI (Debt-to-Income): This captures the "Borderline" logic we enforced
# We add +1 to Income to avoid division by zero (just in case)
df['DTI_Ratio'] = df['Loan_Amount'] / (df['Annual_Income'] + 1)

# Log Income (Standard ML practice to normalize high incomes)
df['Log_Income'] = np.log1p(df['Annual_Income'])

# ---------------------------------------------------------
# 4. SAVE & PREVIEW
# ---------------------------------------------------------
output_file = 'synthetic_data_cleaned_feature_engineered.csv'
df.to_csv(output_file, sep='|', index=False)

print(f"\n✅ Success! Engineered data saved to: {output_file}")
print("-" * 50)
print(df[['Loan_Officer_Note', 'Occupation', 'Risk_Flag', 'DTI_Ratio']].head())
print("-" * 50)

# Check correlation of new features
print("\n🔍 Correlation with Default:")
print(df[['Risk_Flag', 'Has_Asset', 'DTI_Ratio', 'Credit_Score', 'Default_Status']].corr()['Default_Status'])

✅ Loaded 1091 rows.
🚀 Running Smart Feature Extraction...

100%|██████████| 1091/1091 [00:00<00:00, 8175.20it/s]

🧮 Calculating Financial Ratios...

✅ Success! Engineered data saved to: synthetic_data_cleaned_feature_engineered.csv
--------------------------------------------------
                                   Loan_Officer_Note Occupation  Risk_Flag  \
0  Teaching assistant facing sudden hospital bill...  Education          0
1  Photographer inherits art collection easing fi...      Other          0
2  Retail store owner deals daily challenges due ...    Service          0
3  Software developer secures bonus which helps c...       Tech          0
4  Business consultant recently benefited from su...   Business          0

   DTI_Ratio
0   1.333322
1   0.599996
2   1.466647
3   1.874941
4   2.999963
--------------------------------------------------

🔍 Correlation with Default:
Risk_Flag         0.578122
Has_Asset        -0.137505
DTI_Ratio         0.451912
Credit_Score      0.028142
Default_Status    1.000000
Name: Default_Status, dtype: float64

# Fix Formatting
The Bad News (Dirty Data) ⚠️
Your CSV file has formatting errors, likely from the way the text was saved.

Column Name Error: The column is named Has_External_Asset, (with a trailing comma).

Value Errors: The values contain random punctuation:

Expected: Yes, No

Actual: Yes,, No", nan, Yes"

If you feed this directly into a model (like Random Forest), it will treat "Yes" and "Yes," as two completely different categories, which will hurt your accuracy.

3. How to Fix It (Run This Code)
Run this simple cleaning block to fix the punctuation and handle the empty values before you proceed to modeling.

In [ ]:
import pandas as pd

# 1. Load your enriched file
df = pd.read_csv('enriched_data_CPU - enriched_data_CPU.csv', sep='|')

# 2. Fix the Column Name (remove trailing comma)
df.columns = [c.strip().replace(',', '') for c in df.columns]

# 3. Clean the 'Has_External_Asset' column
# This function removes quotes, commas, and handles missing values
def clean_asset(val):
    if pd.isna(val): return "No"        # Fill blanks with No
    val = str(val).lower().strip()
    if 'yes' in val: return 1           # Convert to Number (1)
    return 0                            # Convert to Number (0)

df['Has_External_Asset'] = df['Has_External_Asset'].apply(clean_asset)

# 4. Clean the 'Occupation_Bucket' column
def clean_job(val):
    if pd.isna(val): return "Business"  # Default fallback
    return str(val).strip().replace(',', '').replace('"', '')

df['Occupation_Bucket'] = df['Occupation_Bucket'].apply(clean_job)

# Fix the mixed types: force "No" to become 0, and ensure everything is integer
df['Has_External_Asset'] = df['Has_External_Asset'].replace({'No': 0, 'Yes': 1}).astype(int)

# Now it will be perfect: [0, 1]
print(df['Has_External_Asset'].unique())

# 5. Save the Cleaned Version
df.to_csv('final_clean_dataset.csv', index=False, sep='|')

print("✅ Data is now clean and ready for modeling!")
print(df[['Occupation_Bucket', 'Has_External_Asset']].head())

[1 0]
✅ Data is now clean and ready for modeling!
  Occupation_Bucket  Has_External_Asset
0          Business                   1
1           Retired                   1
2           Medical                   0
3           Student                   0
4          Business                   1

/tmp/ipython-input-2102928086.py:27: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Has_External_Asset'] = df['Has_External_Asset'].replace({'No': 0, 'Yes': 1}).astype(int)

CANCEL (GPU version)

In [ ]:
# ==========================================================
# 1. SETUP & INSTALLATION
# ==========================================================
from google.colab import drive
import os
import pandas as pd
import torch
import re
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
from tqdm import tqdm

# Mount Drive
drive.mount('/content/drive')
!pip install -q transformers torch accelerate tqdm

# Set Project Folder
project_folder = "/content/drive/MyDrive/WIE3007_Project"
if not os.path.exists(project_folder):
    os.makedirs(project_folder)
os.chdir(project_folder)

# Load Data
filename = 'synthetic_financial_data_NOISY (1).csv'
df = pd.read_csv(filename, sep='|')
print(f"✅ Loaded {len(df)} rows.")

# ==========================================================
# 2. LOAD SLM (TinyLlama-1.1B)
# ==========================================================
model_id = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
print("⏳ Loading AI Model...")
tokenizer = AutoTokenizer.from_pretrained(model_id)
pipe = pipeline("text-generation", model=model_id, tokenizer=tokenizer,
                torch_dtype=torch.float16, device_map="auto")

# ==========================================================
# 3. LEAK-PROOF EXTRACTION LOGIC
# ==========================================================
def extract_with_llm(note):
    # We ask for FACTS only, not opinions
    prompt = f"<|system|>\nExtract Job and Asset (Yes/No).</s>\n<|user|>\nNote: {note}</s>\n<|assistant|>\n"
    try:
        # Generate response
        outputs = pipe(prompt, max_new_tokens=35, do_sample=False, return_full_text=False)
        return outputs[0]['generated_text'].strip()
    except:
        return "Unknown | No"

def smart_cleaner(text, original_note):
    """
    Combines LLM output with a strict Keyword Check to fix 'Unknowns'.
    Prevents 'credit' from counting as 'IT'.
    """
    text = text.split('\n')[0].strip()

    # 1. Try to parse LLM output (Format: Job | Asset)
    if '|' in text:
        parts = text.split('|')
        return parts[0].strip(), parts[1].strip()

    # 2. FALLBACK: Smart Regex Search (If LLM fails)
    # We use \b to ensure whole words only (prevents 'credit' matching 'IT')
    note_lower = original_note.lower()

    buckets = {
        'Medical': r'\b(doctor|nurse|clinic|surgeon|dentist|medical|pharmacy|patient)\b',
        'Tech': r'\b(it|tech|software|developer|programmer|data|network|cyber)\b',
        'Education': r'\b(teacher|professor|tutor|academic|faculty|school|university)\b',
        'Business': r'\b(entrepreneur|business|manager|consultant|sales|marketing|executive|accountant|analyst)\b',
        'Trade': r'\b(blue collar|factory|construction|mechanic|plumber|electrician|driver|labor)\b',
        'Service': r'\b(service|designer|artist|chef|writer|journalist|travel|musician)\b',
        'Retired': r'\b(retired|retiree|pension)\b',
        'Student': r'\b(student|graduate|intern|phd)\b'
    }

    found_job = "Other"
    for cat, pattern in buckets.items():
        if re.search(pattern, note_lower):
            found_job = cat
            break

    # Asset check
    asset_pattern = r'\b(inheritance|bonus|venture|trust|dividend|royalty|settlement|stipend|scholarship)\b'
    found_asset = "Yes" if re.search(asset_pattern, note_lower) else "No"

    return found_job, found_asset

# ==========================================================
# 4. RUN FULL PROCESS
# ==========================================================
print(f"🚀 Processing {len(df)} rows... (Approx 5 mins)")
tqdm.pandas()

# Step A: Ask LLM
df['LLM_Raw'] = df['Loan_Officer_Note'].progress_apply(extract_with_llm)

# Step B: Clean & Verify
df[['Occupation_Bucket', 'Has_External_Asset']] = df.apply(
    lambda row: pd.Series(smart_cleaner(row['LLM_Raw'], row['Loan_Officer_Note'])), axis=1
)

# ==========================================================
# 5. SAVE FINAL DATASET
# ==========================================================
output_file = 'enriched_financial_data_FINAL.csv'
df.drop(columns=['LLM_Raw']).to_csv(output_file, sep='|', index=False)

print(f"\n✅ Success! Saved as {output_file}")
print(df[['Occupation_Bucket', 'Has_External_Asset', 'Default_Status']].head(10))

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
✅ Data Loaded: 1146 rows
⏳ Loading AI Model...

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/551 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/608 [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors:   0%|          | 0.00/2.20G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

Device set to use cpu

🚀 Processing 1146 rows... (Approx 5 mins)

  0%|          | 0/1146 [00:00<?, ?it/s]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
 20%|█▉        | 226/1146 [1:28:42<5:52:17, 22.98s/it]

faster model

In [ ]:
# ==========================================================
# 1. SETUP
# ==========================================================
from google.colab import drive
import os
import pandas as pd
import torch
import re
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
from tqdm.auto import tqdm

# Mount Drive
drive.mount('/content/drive')

# Load Data
project_folder = "/content/drive/MyDrive/WIE3007_Project"
filename = 'synthetic_financial_data_NOISY (1).csv'
path = os.path.join(project_folder, filename)

if os.path.exists(path):
    df = pd.read_csv(path, sep='|')
    print(f"✅ Data Loaded: {len(df)} rows")
else:
    print("❌ File not found. Please check path.")

# ==========================================================
# 2. LOAD QWEN-0.5B (The Fastest Modern SLM)
# ==========================================================
# This model is 2x smaller than TinyLlama but smarter
model_id = "Qwen/Qwen2.5-0.5B-Instruct"

print(f"⏳ Loading {model_id}...")
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    device_map="auto",
    torch_dtype=torch.float16
)

# Initialize pipeline with BATCHING enabled
pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    batch_size=32, # Process 32 rows at once (Huge speedup)
    truncation=True
)
print("✅ Model Loaded!")

# ==========================================================
# 3. HYBRID EXTRACTION (AI for Job + Regex for Asset)
# ==========================================================
# We use AI to classify the Job because it's hard.
# We use Regex for Assets because it's instant and error-proof.

def build_prompts(notes):
    """Generates a list of prompts for batch processing"""
    prompts = []
    for note in notes:
        # Strict Prompt for Qwen
        msg = [
            {"role": "system", "content": "Classify the borrower's job into ONE category: [Medical, Tech, Education, Business, Trade, Service, Retired, Student]. Reply with ONLY the word."},
            {"role": "user", "content": note}
        ]
        text = tokenizer.apply_chat_template(msg, tokenize=False, add_generation_prompt=True)
        prompts.append(text)
    return prompts

def get_asset_regex(note):
    """Instant rule-based extraction for assets"""
    note = str(note).lower()
    keywords = ['inheritance', 'bonus', 'venture', 'trust', 'dividend', 'royalty', 'settlement']
    return "Yes" if any(k in note for k in keywords) else "No"

# ==========================================================
# 4. RUN BATCH INFERENCE
# ==========================================================
print(f"🚀 Processing {len(df)} rows with Batch Size 32...")

# 1. Prepare prompts
prompts = build_prompts(df['Loan_Officer_Note'].tolist())

# 2. Run AI (The heavy lifting)
# This loop feeds batches to the GPU efficiently
occupations = []
for out in tqdm(pipe(prompts, max_new_tokens=10, do_sample=False, return_full_text=False), total=len(prompts)):
    occupations.append(out[0]['generated_text'].strip())

# 3. Apply Regex (Instant)
df['Occupation_Raw'] = occupations
df['Has_External_Asset'] = df['Loan_Officer_Note'].apply(get_asset_regex)

# ==========================================================
# 5. CLEANUP & SAVE
# ==========================================================
def clean_job(val):
    # Map AI output to strict buckets just in case
    val = val.lower()
    if 'medical' in val or 'doctor' in val: return 'Medical'
    if 'tech' in val or 'it' in val: return 'Tech'
    if 'education' in val or 'teacher' in val: return 'Education'
    if 'business' in val or 'entrepreneur' in val: return 'Business'
    if 'trade' in val or 'blue' in val: return 'Trade'
    if 'service' in val: return 'Service'
    if 'retire' in val: return 'Retired'
    if 'student' in val: return 'Student'
    return 'Business' # Default fallback if AI is unsure (safe bet)

df['Occupation_Bucket'] = df['Occupation_Raw'].apply(clean_job)

# Save
output_file = os.path.join(project_folder, 'enriched_data_FAST.csv')
df.drop(columns=['Occupation_Raw']).to_csv(output_file, sep='|', index=False)

print(f"\n✅ Done! Saved to: {output_file}")
print(df[['Occupation_Bucket', 'Has_External_Asset']].head(10))

WARNING:torchao.kernel.intmm:Warning: Detected no triton, on systems without Triton certain kernels will not work

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
✅ Data Loaded: 1146 rows
⏳ Loading Qwen/Qwen2.5-0.5B-Instruct...

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/659 [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors:   0%|          | 0.00/988M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

Device set to use cpu

✅ Model Loaded!
🚀 Processing 1146 rows with Batch Size 32...

The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

KeyboardInterrupt:

# OLD VERSION

In [ ]:
# ================================
# STEP 5: Controlled generation
# ================================
TARGET_ROWS = 100  # Small seed for CTGAN
BATCH_SIZE = 10    # Batch size

header = [
    "Customer_ID", "Age", "Annual_Income", "Credit_Score",
    "Loan_Amount", "Loan_Term_Months", "Loan_Officer_Note",
    "Default_Status"
]

rows = []

print(f"🚀 Starting generation of {TARGET_ROWS} seed rows...")

while len(rows) < TARGET_ROWS:
    prompt = build_prompt(BATCH_SIZE)

    output = generator(
        prompt,
        max_new_tokens=1024,
        do_sample=True,
        temperature=0.7,
        top_p=0.9,
        repetition_penalty=1.1,
        return_full_text=False
    )

    lines = output[0]["generated_text"].strip().split("\n")

    current_batch_count = 0
    for line in lines:
        values = [v.strip() for v in line.split("|")]
        if len(values) == len(header):
            rows.append(values)
            current_batch_count += 1

    print(f"   Progress: {len(rows)}/{TARGET_ROWS} rows (Added {current_batch_count} valid rows)")

# ================================
# STEP 6: Save Seed CSV
# ================================
import csv

seed_file = "seed_financial_data.csv"

# Truncate if we generated too many (e.g. 105 instead of 100)
final_rows = rows[:TARGET_ROWS]

with open(seed_file, "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerow(header)
    writer.writerows(final_rows)

print(f"\n✅ Seed dataset saved as: {seed_file}")

🚀 Starting generation of 100 seed rows...

KeyboardInterrupt:

In [ ]:
# ================================
# STEP 9: Generate Full Dataset (Run this!)
# ================================
from tqdm import tqdm

# 1. Setup File and Header
output_file = "synthetic_financial_data_RAW.csv"
header = [
    "Customer_ID", "Age", "Annual_Income", "Credit_Score",
    "Loan_Amount", "Loan_Term_Months", "Loan_Officer_Note", "Default_Status"
]

with open(output_file, "w") as f:
    f.write("|".join(header) + "\n")

print(f"✅ Initialized {output_file} with headers.")

# 2. Run Generation Loop
batch_size = 50
total_batches = 20  # 20 * 50 = 1000 rows

print("⏳ Starting Generation...")

for i in tqdm(range(total_batches)):
    prompt = build_prompt(batch_size) # Uses your NEW perfect prompt

    sequences = generator(
        prompt,
        max_new_tokens=2048,
        do_sample=True,
        temperature=0.7,
        top_p=0.95,
        return_full_text=False
    )

    generated_text = sequences[0]['generated_text']

    # Append to file
    with open(output_file, "a") as f:
        for line in generated_text.strip().split('\n'):
            if "|" in line and "Customer_ID" not in line:
                f.write(line + "\n")

print("🎉 DONE! Download your file from the left sidebar.")

In [ ]:
# ================================
# STEP 7: Verify dataset
# ================================
import pandas as pd

try:
    # CHANGE: Use 'seed_file' instead of 'output_file'
    df = pd.read_csv(seed_file)
    print("Dataset Shape:", df.shape)
    print(df.head())
except Exception as e:
    print("Error reading CSV:", e)

Dataset Shape: (100, 10)
                         Customer_ID  Age Annual_Income Credit_Score  \
0  ?<>:lmnopQRSTuvXYZABCD*&&(&)([]}{  }{}            45        75000
1                               C003   45         78000          810
2                       CUSTOMER_010   38         60000          720
3                        Alice Smith   35        76,000          790
4                           John Doe   45       115,000          680

  Loan_Amount Loan_Term_Months  \
0         760            40000
1       50000               48
2       65000               36
3      50,000               36
4      30,000               12

                                   Loan_Officer_Note  \
0                                                 48
1  Long term employee with excellent performance ...
2  Has recently completed additional education th...
3  Good risk profile; consistent repayments in pa...
4  Moderately risky but good assets secured by pr...

                                      Default_Status  \
0  Prudent spending habits indicate reliable paym...
1                                                NaN
2                                                  0
3                                                  0
4                                                  1

                                          Risk_Level  \
0                                                  0
1                                                  0
2  Medium[/INST] The provided input follows all s...
3                                                Low
4                                             Medium

                                    Customer_Segment
0                                                Low
1                                                Low
2  ', containing values within their respective r...
3                                Young professionals
4             Middle management salaried individuals

In [ ]:
# ================================
# STEP 8: Train CTGAN & Mass Produce (ROBUST FIX)
# ================================
from ctgan import CTGAN
import pandas as pd
import numpy as np

print("🚀 Starting CTGAN Training (The 'Cloning' Phase)...")

# 1. Load the "Seed" data
data = pd.read_csv("seed_financial_data.csv")
print(f"Original seed data shape: {data.shape}")

# --- FIX START: DATA CLEANING ---

# A. Drop ID column (AI doesn't need to learn random IDs)
if "Customer_ID" in data.columns:
    data = data.drop(columns=["Customer_ID"])

# B. Force 'Default_Status' to be numbers (0 or 1).
# This removes the text garbage like "Moderately new..." that accidentally got into this column.
data['Default_Status'] = pd.to_numeric(data['Default_Status'], errors='coerce')

# C. Force other numeric columns to be numbers
numeric_cols = ["Age", "Annual_Income", "Credit_Score", "Loan_Amount", "Loan_Term_Months"]
for col in numeric_cols:
    data[col] = pd.to_numeric(data[col], errors='coerce')

# D. Drop any rows that now have empty values (NaN)
data = data.dropna()

print(f"Cleaned data shape: {data.shape} (Bad rows removed)")
# --- FIX END ---

# 2. Define columns.
# Note: We removed Customer_ID. CTGAN handles text (like 'Risk_Level') automatically.
discrete_columns = [
    'Default_Status',
    'Loan_Term_Months',
    'Loan_Officer_Note' # treating notes as categories (will repeat common notes)
]

# 3. Initialize and Train
ctgan_model = CTGAN(epochs=300, verbose=True)
ctgan_model.fit(data, discrete_columns)

print("✅ CTGAN Trained! Now generating massive dataset...")

# ================================
# STEP 9: Generate Massive Data
# ================================
TOTAL_REQUIRED = 1500
CHUNK_SIZE = 100
output_massive_file = "synthetic_financial_data_FINAL.csv"

# Create file with header
# We need to add Customer_ID back manually since we dropped it for training
header = ["Customer_ID"] + list(data.columns)
pd.DataFrame(columns=header).to_csv(output_massive_file, index=False)

count = 0
while count < TOTAL_REQUIRED:
    # Generate a chunk
    synthetic_data = ctgan_model.sample(CHUNK_SIZE)

    # Add fake Customer_IDs back (e.g., SYN-001, SYN-002...)
    start_id = count + 1
    ids = [f"SYN-{i:06d}" for i in range(start_id, start_id + CHUNK_SIZE)]
    synthetic_data.insert(0, "Customer_ID", ids)

    # Round numeric columns (CTGAN might give Age=29.432, we want 29)
    synthetic_data["Age"] = synthetic_data["Age"].round(0).astype(int)
    synthetic_data["Credit_Score"] = synthetic_data["Credit_Score"].round(0).astype(int)
    synthetic_data["Default_Status"] = synthetic_data["Default_Status"].round(0).abs().astype(int) # Ensure 0 or 1

    # Append to file
    synthetic_data.to_csv(output_massive_file, mode='a', header=False, index=False)

    count += CHUNK_SIZE
    print(f"   Generated {count}/{TOTAL_REQUIRED} rows...")

print(f"\n🎉 DONE! Massive dataset saved to: {output_massive_file}")

🚀 Starting CTGAN Training (The 'Cloning' Phase)...
Original seed data shape: (100, 8)
Cleaned data shape: (100, 7) (Bad rows removed)

Gen. (0.00) | Discrim. (0.00):   0%|          | 0/300 [00:00<?, ?it/s]/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:841: UserWarning: Attempting to run cuBLAS, but there was no current CUDA context! Attempting to set the primary context... (Triggered internally at /pytorch/aten/src/ATen/cuda/CublasHandlePool.cpp:270.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Gen. (0.64) | Discrim. (-0.06): 100%|██████████| 300/300 [00:09<00:00, 32.98it/s]

✅ CTGAN Trained! Now generating massive dataset...
   Generated 100/1500 rows...
   Generated 200/1500 rows...
   Generated 300/1500 rows...
   Generated 400/1500 rows...
   Generated 500/1500 rows...
   Generated 600/1500 rows...
   Generated 700/1500 rows...
   Generated 800/1500 rows...
   Generated 900/1500 rows...
   Generated 1000/1500 rows...
   Generated 1100/1500 rows...
   Generated 1200/1500 rows...
   Generated 1300/1500 rows...
   Generated 1400/1500 rows...
   Generated 1500/1500 rows...

🎉 DONE! Massive dataset saved to: synthetic_financial_data_FINAL.csv

**Feature Extraction**

In [ ]:
import pandas as pd
import numpy as np

# 1. Load your current dataset
df = pd.read_csv("synthetic_financial_data_FINAL.csv")
print(f"Original shape: {df.shape}")

# ==========================================
# FIX 1: Handle Negative Numbers
# ==========================================
# We take the absolute value (convert -5000 to 5000)
df['Annual_Income'] = df['Annual_Income'].abs()
df['Loan_Amount'] = df['Loan_Amount'].abs()

# ==========================================
# FIX 2: Repair Credit Scores
# ==========================================
# The current scores are garbage (-3000 to 5000).
# We will REGENERATE them nicely based on 'Risk_Level' so they make sense.

def fix_credit_score(row):
    risk = row['Risk_Level']
    if risk == 'Low':
        return np.random.randint(720, 850)  # Great score
    elif risk == 'Medium':
        return np.random.randint(580, 719)  # Average score
    else: # High Risk
        return np.random.randint(300, 579)  # Poor score

df['Credit_Score'] = df.apply(fix_credit_score, axis=1)

# ==========================================
# FIX 3: Clean Text & Ages
# ==========================================
# Clip Age to be realistic (18 to 80)
df['Age'] = df['Age'].clip(18, 80)

# Remove rows where the AI pasted the prompt instructions (The "[/INST]" leak)
df = df[~df['Customer_Segment'].astype(str).str.contains("INST")]

# Shorten any crazy long text in Customer_Segment (keep first 30 chars)
df['Customer_Segment'] = df['Customer_Segment'].apply(lambda x: x[:30] if isinstance(x, str) else x)

# ==========================================
# SAVE CLEANED FILE
# ==========================================
df.to_csv("synthetic_financial_data_CLEANED.csv", index=False)
print("✅ Fixed! Saved as 'synthetic_financial_data_CLEANED.csv'")
print(df.describe())

Original shape: (1500, 10)
✅ Fixed! Saved as 'synthetic_financial_data_CLEANED.csv'
               Age  Annual_Income  Credit_Score    Loan_Amount  \
count  1500.000000    1500.000000   1500.000000    1500.000000
mean     34.684667  170436.058110    642.634000   56482.699862
std      15.073621   69498.656820    147.971483   29231.374422
min      18.000000     983.624962    300.000000     117.065085
25%      20.000000  118943.857201    558.750000   35338.525515
50%      32.000000  176989.444428    671.000000   58192.224622
75%      46.000000  224537.981265    762.000000   78646.475207
max      80.000000  304218.836912    849.000000  131248.530024

       Loan_Term_Months  Default_Status
count       1500.000000     1500.000000
mean          45.545333        0.298000
std           17.980753        0.457532
min           12.000000        0.000000
25%           36.000000        0.000000
50%           48.000000        0.000000
75%           60.000000        1.000000
max           84.000000        1.000000

# Data Generation (Iskandar version 1.0)

In [ ]:
!pip install ctgan

Collecting ctgan
  Downloading ctgan-0.11.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from ctgan) (2.0.2)
Requirement already satisfied: pandas>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from ctgan) (2.2.2)
Requirement already satisfied: torch>=2.3.0 in /usr/local/lib/python3.12/dist-packages (from ctgan) (2.9.0+cu126)
Requirement already satisfied: tqdm<5,>=4.29 in /usr/local/lib/python3.12/dist-packages (from ctgan) (4.67.1)
Collecting rdt>=1.14.0 (from ctgan)
  Downloading rdt-1.19.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.1.1->ctgan) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.1.1->ctgan) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.1.1->ctgan) (2025.3)
Requirement already satisfied: scipy>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from rdt>=1.14.0->ctgan) (1.16.3)
Requirement already satisfied: scikit-learn>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from rdt>=1.14.0->ctgan) (1.6.1)
Collecting Faker!=37.11.0,>=17 (from rdt>=1.14.0->ctgan)
  Downloading faker-40.1.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan) (3.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.1.1->ctgan) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.3.1->rdt>=1.14.0->ctgan) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.3.1->rdt>=1.14.0->ctgan) (3.6.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.3.0->ctgan) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.3.0->ctgan) (3.0.3)
Downloading ctgan-0.11.1-py3-none-any.whl (25 kB)
Downloading rdt-1.19.0-py3-none-any.whl (74 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.4/74.4 kB 3.9 MB/s eta 0:00:00
Downloading faker-40.1.0-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 50.2 MB/s eta 0:00:00
Installing collected packages: Faker, rdt, ctgan
Successfully installed Faker-40.1.0 ctgan-0.11.1 rdt-1.19.0

In [ ]:
# --- Install CTGAN if not already installed ---
# !pip install ctgan --upgrade

import pandas as pd
import json
from concurrent.futures import ThreadPoolExecutor, as_completed
import google.generativeai as genai
from ctgan import CTGAN  # Modern CTGAN API

# --- Configure Gemini API ---
api_key = "AIzaSyDA2q18PVxbUi78J2l020M5c8oW_CKDWDo"
genai.configure(api_key=api_key)
model = genai.GenerativeModel('gemini-2.5-flash')

# --- Function to generate a batch from Gemini ---
def generate_financial_data_batch(batch_size, batch_id):
    prompt = f"""
    You are a data generator.
    Generate {batch_size} unique, realistic financial records for a credit risk dataset (Batch #{batch_id}).
    Output ONLY a valid JSON list of objects.

    Each object must contain these keys:
    "age": (int 21-70),
    "monthly_income": (int 1500-20000),
    "credit_utilization_ratio": (float 0.1-1.0),
    "loan_amount": (int 1000-50000),
    "loan_duration_months": (choice 12,24,36,48,60),
    "num_late_payments": (int 0-10),
    "existing_loans_count": (int 0-5),
    "account_tenure_years": (int 0-20),
    "employment_type": ("Salaried","Self-Employed","Student","Unemployed"),
    "education_level": ("High School","Diploma","Bachelor","Master"),
    "marital_status": ("Single","Married","Divorced"),
    "region": ("Urban","Suburban","Rural"),
    "customer_financial_statement": (A unique 1-sentence statement in first person about their money),
    "sentiment": ("Positive","Neutral","Negative"),
    "financial_stress_level": ("Low","Medium","High"),
    "risk_category": ("Low Risk","Watchlist","High Risk"),
    "default_risk": (0 or 1)
    """
    try:
        response = model.generate_content(prompt)
        raw_text = response.text.strip().replace('```json', '').replace('```', '')
        return json.loads(raw_text)
    except Exception as e:
        print(f"Error in batch {batch_id}: {e}")
        return []

# --- Generate Seed Data with Gemini ---
SEED_RECORDS = 300
BATCH_SIZE = 50
NUM_BATCHES = (SEED_RECORDS + BATCH_SIZE - 1) // BATCH_SIZE

all_records = []
print("Generating seed data with Gemini...")
with ThreadPoolExecutor(max_workers=5) as executor:
    future_to_batch = {
        executor.submit(generate_financial_data_batch, BATCH_SIZE, i+1): i+1
        for i in range(NUM_BATCHES)
    }
    for future in as_completed(future_to_batch):
        batch_id = future_to_batch[future]
        try:
            batch_data = future.result()
            if batch_data:
                all_records.extend(batch_data)
                print(f"Batch {batch_id} completed. Total records: {len(all_records)}")
        except Exception as e:
            print(f"Batch {batch_id} failed with exception: {e}")

df_seed = pd.DataFrame(all_records)
print("Seed data generated. Sample:")
print(df_seed.head())

# --- Use CTGAN to expand dataset ---
categorical_columns = [
    "loan_duration_months",
    "employment_type",
    "education_level",
    "marital_status",
    "region",
    "sentiment",
    "financial_stress_level",
    "risk_category",
    "default_risk",
    "customer_financial_statement" # <-- Added this line
]

/usr/local/lib/python3.12/dist-packages/google/colab/_import_hooks/_hook_injector.py:55: FutureWarning:

All support for the `google.generativeai` package has ended. It will no longer be receiving
updates or bug fixes. Please switch to the `google.genai` package as soon as possible.
See README for more details:

https://github.com/google-gemini/deprecated-generative-ai-python/blob/main/README.md

  loader.exec_module(module)

Generating seed data with Gemini...
Batch 1 completed. Total records: 57

In [ ]:
print("Training CTGAN on seed data...")
ctgan = CTGAN(epochs=300)  # Modern CTGAN
ctgan.fit(df_seed, discrete_columns=categorical_columns)

# Generate full synthetic dataset
TOTAL_RECORDS = 1500
synthetic_data = ctgan.sample(TOTAL_RECORDS)
print(f"Synthetic dataset generated. Total records: {len(synthetic_data)}")

# --- Save as CSV ---
output_file = "synthetic_credit_risk_data.csv"
synthetic_data.to_csv(output_file, index=False)
print(f"Data saved to {output_file}")

Training CTGAN on seed data...

TypeError: Could not convert string 'My finances feel stable and I'm comfortably saving for the future.I'm trying hard to manage my debts but it's often a struggle.My investments are growing steadily, providing great peace of mind.I'm deeply worried about making ends meet and falling further behind on payments.Things are generally okay, though I always keep an eye on my budget.It's tough juggling studies and expenses; I often feel stretched financially.My financial future is secure, and I'm planning for early retirement.I'm managing okay, but unexpected costs are always a concern for my business.My wealth management plan is robust, ensuring a prosperous future for my family.I'm drowning in bills and fear I'll never catch up; it's a constant struggle.I feel financially comfortable and enjoy my retirement planning.I'm making progress on my debts but it feels like a slow uphill battle.My business finances are solid and I'm looking to expand soon.I'm constantly worried about unexpected expenses pushing me over the edge.My financial portfolio is strong, providing great security and growth.Every month is a financial struggle just to keep my head above water.I'm generally comfortable but always looking for ways to improve my savings.My income varies, which makes consistent debt payments challenging.I've carefully managed my assets to ensure a comfortable future.I'm constantly stressed about money and see no clear path out of this situation.My financial planning ensures I am well-prepared for any future event.I'm managing my finances, but a larger loan would definitely stretch my budget.My financial situation is a disaster, I'm barely surviving day-to-day.My business is stable, and I'm looking forward to a comfortable retirement.I'm in an excellent financial position and constantly seeking new investment opportunities.I'm finding it hard to get ahead with all my existing financial commitments.My financial situation is robust, and I'm planning for future generations.I'm struggling intensely to pay my bills and feel completely overwhelmed.My retirement is fully funded, and I enjoy a life free from financial worries.My finances are acceptable, but I'm cautious about taking on more debt.I'm under significant financial pressure trying to manage school and living costs.I feel financially secure and am planning for my future post-retirement.My debts are overwhelming, and I'm desperately seeking employment.I'm in a great financial position, always on the lookout for smart investments.Managing my finances is a delicate balance, but I'm slowly improving.My financial future is robust, allowing me to enjoy my life to the fullest.I'm overwhelmed by debt and constantly worried about my financial stability.Finances are pretty good, though I'm always looking for smart savings options.My financial portfolio is strong, ensuring peace of mind for my family.It's a constant struggle to keep up with bills, often leaving me stressed.My financial legacy is well-established, providing for future generations.Finances are decent, but I'm always mindful of unexpected business costs.My retirement is secure, and I have more than enough for my golden years.I'm in a dire financial situation and desperately need a stable income.My finances are managed well, and I'm comfortable with my savings.It's challenging to stabilize my finances with my fluctuating income.I have carefully planned my retirement, ensuring a comfortable future.My financial situation is extremely precarious; I need assistance.My assets are growing consistently, securing my family's financial future.I'm generally doing alright, but I'm careful with every financial decision.I'm struggling to find work and my financial situation is rapidly deteriorating.My financial affairs are well in order, providing peace of mind.I'm facing immense financial pressure and finding it hard to cope.My finances are robust with a strong monthly income of $12890, allowing me to save effectively.I'm keeping up with my 3 existing loans and managing my credit utilization at 68% without major issues.My financial situation is dire; my monthly income of $2100 is simply not enough for my expenses.I feel very secure financially, with my credit utilization at a healthy 42% and no payment issues.My financial situation is stable, and I'm ensuring all payments are made, despite having 3 late payments previously.I'm overwhelmed by my debts; my credit utilization is a very high 99% and I'm behind on payments.With 12 years of account history, I've built a solid financial foundation and feel great about my future.I'm steadily working on my financial goals, maintaining an acceptable credit utilization and payment history.It's becoming increasingly difficult to make ends meet, and my numerous late payments are a major concern.My financial health is top-notch; I have ample savings and no concerns about my existing debt.My financial status is average; I'm balancing my income and outgoings.I'm extremely worried about paying back my $18000 loan, especially with my current financial stress.I'm in an excellent financial position, consistently managing my income and expenses with ease.I'm cautiously optimistic about my financial future, focusing on consistent payments.I am under severe financial stress, constantly worried about how to cover my next bill.I'm financially stable and making smart choices, especially with my 18000 income.I'm keeping up with my 2 existing loans and managing my credit utilization at 70% without major issues.My finances are a mess, and I don't see a clear path forward with all these obligations.Everything is smooth financially, and I am confident in my ability to handle any expenses.My financial status is decent, and I try to avoid any financial stress.I'm at my breaking point financially; I just received another late payment notice.I comfortably manage my 0 existing loans and my credit score is excellent with only 0 late payments.My financial state is average; I'm balancing my income and outgoings.I'm really struggling with my 1 existing loans and the 5 late payments are weighing heavily on me.Managing my money is easy, and I'm on track to pay off my $12000 loan ahead of schedule.I'm meeting my financial obligations, though there's not much left for significant savings.My financial health is poor, and I desperately need help managing my loans.I have strong financial discipline, keeping my credit utilization low and all payments on time.My financial situation is stable, and I'm ensuring all payments are made, despite having 2 late payments previously.I regret taking on this $20000 loan, as it's pushing me into deep financial trouble.I'm in an excellent financial position, consistently managing my income and expenses with ease.My financial status is decent, and I try to avoid any financial stress.My financial health is poor, and I desperately need help managing my loans.I'm financially stable and making smart choices, especially with my 19000 income.Things are generally fine with my finances; I'm diligently making payments for my 60-month loan.I'm at my breaking point financially; I just received another late payment notice.I'm in an excellent financial position, consistently managing my income and expenses with ease.My financial state is average; I'm balancing my income and outgoings.I regret taking on this $22000 loan, as it's pushing me into deep financial trouble.I'm financially stable and making smart choices, especially with my 17000 income.I'm cautiously optimistic about my financial future, focusing on consistent payments.I'm really struggling with my 2 existing loans and the 4 late payments are weighing heavily on me.My finances are robust with a strong monthly income of $10000, allowing me to save effectively.I'm diligently making payments for my 48-month loan, although my credit utilization is a bit high.My financial situation is dire; my monthly income of $1950 is simply not enough for my expenses.I feel very secure financially, with my credit utilization at a healthy 17% and no payment issues.My financial status is average; I'm balancing my income and outgoings.I'm extremely worried about paying back my $10000 loan, especially with my current financial stress.Managing my money is easy, and I'm on track to pay off my $6000 loan ahead of schedule.I'm keeping up with my 2 existing loans and managing my credit utilization at 67% without major issues.I'm really struggling with my 2 existing loans and the 6 late payments are weighing heavily on me.I have strong financial discipline, keeping my credit utilization low and all payments on time.My financial state is average; I'm balancing my income and outgoings.My financial situation is dire; my monthly income of $1800 is simply not enough for my expenses.My finances are stable, and I'm comfortably saving for my children's education.I'm trying my best to manage my credit card debt, but it's often a struggle.My investments are growing steadily, and I have no financial worries.I am constantly overwhelmed by bills and feel like I'm drowning in debt after losing my job.My income fluctuates, so I budget strictly to meet all my financial responsibilities.I'm trying to manage my student loans while also covering living expenses.Approaching retirement, I feel secure with my current savings and minimal debt.Despite my steady job, managing multiple loan payments is becoming incredibly stressful.I'm confidently investing in my future and maintaining a healthy financial outlook.I've hit a rough patch, and it feels like I'm constantly behind on my payments.I'm juggling my part-time job and tuition, so money is always tight.My retirement planning is on track, and I'm very comfortable financially.I'm carefully budgeting to ensure I can provide for my family while paying off my loan.The business isn't doing well, and I'm very concerned about defaulting on my obligations.My financial portfolio is strong, and I anticipate a prosperous retirement.I'm desperately looking for work as my savings are depleted and bills are piling up.My family's financial future is secure thanks to careful planning and a stable income.I'm struggling to balance fluctuating income with several ongoing loan commitments.My financial planning ensures a comfortable retirement, free from debt.I'm completely overwhelmed by my debts and don't see a way out right now.I'm making steady progress towards my financial goals, keeping debt low.Managing my finances is challenging, but I'm determined to avoid any further late payments.I'm carefully monitoring my spending to stay within my student budget and manage my small loan.I'm cautious about my finances as I prepare for retirement, aiming to keep my obligations low.My financial situation is robust, allowing me to plan for significant long-term investments.I'm facing severe financial distress and don't know how I'll ever repay all my debts.My financial future is secured, and I manage my assets very efficiently.My business income is unpredictable, causing stress about upcoming payments.I'm diligently working towards my savings goals and keeping my finances in order.It's tough starting out, but I'm learning to manage my first small credit line responsibly.My retirement is funded, and I live comfortably within my means.I've hit rock bottom financially and have no hope of making my next loan payment.I maintain excellent financial health, focusing on long-term wealth creation.My business has some unexpected costs, making debt repayment a tightrope walk.I'm finding it hard to manage my expenses and credit, often falling behind.I'm enjoying my senior years with minimal financial commitments and good savings.My financial situation is a constant source of anxiety, with bills often exceeding my income.I'm confident in my ability to manage this significant loan thanks to my robust financial standing.I'm carefully navigating a period of tight cash flow, aiming to clear my debts soon.With no income, I'm struggling immensely to prevent all my accounts from defaulting.My financial outlook is bright, with good savings and manageable debt for retirement.I'm working diligently to reduce my credit card balances and improve my financial standing.I am financially secure and focusing on maximizing my long-term wealth growth.My unpredictable income makes it incredibly hard to keep up with all my loan payments.I'm confidently managing my finances and making progress towards significant savings.I'm being careful with my spending to manage my limited income as a student.My finances are incredibly robust, and I am enjoying a comfortable retirement.I feel trapped by my mounting debts and the constant struggle to find stable employment.I'm well on my way to achieving my financial independence goals with careful planning.I'm focused on improving my business's profitability to ease my current financial pressures.Managing my finances is a constant uphill battle with limited income and existing debt.I am financially thriving and enjoying the rewards of a lifetime of responsible saving.My finances are strong, allowing me to save 1324 monthly for my future. (Ref:4645)The 6 late payments recently are a huge concern for my financial future. (Ref:7573)I manage my money well and have no late payments, which gives me peace of mind. (Ref:8859)I'm managing my budget, though sometimes it's a tight squeeze with my 13745 loan. (Ref:8447)Being unemployed means I'm barely making ends meet and am very worried about my debts. (Ref:7726)With a high income of $15890, I'm investing heavily and feel financially secure. (Ref:4238)Still building my financial stability after 0 years, cautiously optimistic. (Ref:9312)I'm focused on paying down some debts, aiming for better financial footing in the next year. (Ref:3967)My credit utilization is very low at 11%, reflecting excellent financial health. (Ref:5025)I'm struggling with high credit utilization of 95% and 4 late payments. (Ref:5896)It's a balance between spending and saving, and I try to make smart choices. (Ref:8842)I've been able to build up a substantial emergency fund over my 12 years of banking. (Ref:6886)My financial situation keeps me up at night, especially with such a high loan amount of $15000. (Ref:4643)Saving for my long-term goals is going smoothly, feeling confident about my financial path. (Ref:5085)I feel overwhelmed by my 3 existing loans and mounting bills. (Ref:9318)My finances are strong, allowing me to save 1146 monthly for my future. (Ref:2910)My financial situation is stable for now, but I'm trying to save more consistently. (Ref:9242)My low income of $2500 makes it nearly impossible to manage my current financial obligations. (Ref:2543)Still building my financial stability after 4 years, cautiously optimistic. (Ref:8857)My finances are strong, allowing me to save 1056 monthly for my future. (Ref:1020)I'm struggling with high credit utilization of 85% and 3 late payments. (Ref:5081)I'm managing my budget, though sometimes it's a tight squeeze with my 20000 loan. (Ref:4231)With a high income of $19000, I'm investing heavily and feel financially secure. (Ref:6806)My financial situation keeps me up at night, especially with such a high loan amount of $45000. (Ref:9276)I'm managing my budget, though sometimes it's a tight squeeze with my 6000 loan. (Ref:1768)Saving for my long-term goals is going smoothly, feeling confident about my financial path. (Ref:2135)Balancing 3 loans requires careful planning, but I'm keeping up. (Ref:3968)My low income of $1500 makes it nearly impossible to manage my current financial obligations. (Ref:5733)My credit utilization is very low at 19%, reflecting excellent financial health. (Ref:9284)My financial situation is stable for now, but I'm trying to save more consistently. (Ref:5070)I've been able to build up a substantial emergency fund over my 10 years of banking. (Ref:8774)The 8 late payments recently are a huge concern for my financial future. (Ref:6449)I'm managing my budget, though sometimes it's a tight squeeze with my 10000 loan. (Ref:9275)My finances are strong, allowing me to save 1729 monthly for my future. (Ref:3863)My financial situation keeps me up at night, especially with such a high loan amount of $18000. (Ref:8773)Balancing 2 loans requires careful planning, but I'm keeping up. (Ref:8864)I feel overwhelmed by my 5 existing loans and mounting bills. (Ref:6390)My credit utilization is very low at 15%, reflecting excellent financial health. (Ref:3918)Still building my financial stability after 0 years, cautiously optimistic. (Ref:9998)I've been able to build up a substantial emergency fund over my 15 years of banking. (Ref:6887)My low income of $2300 makes it nearly impossible to manage my current financial obligations. (Ref:1021)I'm managing my budget, though sometimes it's a tight squeeze with my 17000 loan. (Ref:7572)With a high income of $19500, I'm investing heavily and feel financially secure. (Ref:2909)My financial situation keeps me up at night, especially with such a high loan amount of $25000. (Ref:6805)I manage my money well and have no late payments, which gives me peace of mind. (Ref:5084)I'm struggling with high credit utilization of 80% and 6 late payments. (Ref:7574)My financial situation is stable for now, but I'm trying to save more consistently. (Ref:3966)My finances are strong, allowing me to save 1957 monthly for my future. (Ref:2544)The 6 late payments recently are a huge concern for my financial future. (Ref:6389)I'm managing my budget, though sometimes it's a tight squeeze with my 20000 loan. (Ref:2134)I feel overwhelmed by my 3 existing loans and mounting bills. (Ref:8844)My credit utilization is very low at 28%, reflecting excellent financial health. (Ref:9243)I'm struggling with high credit utilization of 95% and 4 late payments. (Ref:5082)Balancing 3 loans requires careful planning, but I'm keeping up. (Ref:1767)My low income of $1800 makes it nearly impossible to manage my current financial obligations. (Ref:7727)With a high income of $13000, I'm investing heavily and feel financially secure. (Ref:4644)My finances are very stable, and I'm comfortable with my savings. (Ref:1)I'm constantly worried about making ends meet, and falling behind on payments is a real fear. (Ref:2)I feel confident about my financial future and enjoy managing my money. (Ref:3)My debt feels overwhelming, and I don't see a clear path to financial stability. (Ref:4)I manage to pay my bills on time, though saving more is a constant challenge. (Ref:5)Budgeting comes easily to me, and I rarely worry about unexpected expenses. (Ref:6)I'm struggling to keep up with my bills and feel very anxious about my financial future. (Ref:7)I have some financial difficulties, and it sometimes keeps me up at night. (Ref:8)I'm on track with my financial goals and regularly contribute to my investments. (Ref:9)Unexpected expenses always seem to put me in a difficult financial spot, and I never seem to catch a break. (Ref:10)I'm making good progress towards my financial goals, though I still need to be mindful of my spending. (Ref:11)I often worry about my monthly expenses, and I need to budget very carefully. (Ref:12)My financial situation is good, and I am slowly building my savings. (Ref:13)My finances are very stressful, but I am trying to stay calm and figure things out. (Ref:14)My debt feels overwhelming, and I don't see a clear path to financial stability. (Ref:15)I have a handle on my money, and I'm not overly concerned. (Ref:16)I'm under significant financial strain, but keeping a level head is important to me. (Ref:17)My income covers my expenses well, but I aim to save more consistently. (Ref:18)I'm constantly worried about making ends meet, and falling behind on payments is a real fear. (Ref:19)My spending is well-managed, and I'm not actively struggling. (Ref:20)The financial pressure is immense, yet I'm working hard to find a solution. (Ref:21)I am comfortably managing my finances and working towards

#Data Generation (Iskandar version 2.0)

In [ ]:
!pip install -q google-generativeai

In [ ]:
import google.generativeai as genai
import pandas as pd
import json
import time
from concurrent.futures import ThreadPoolExecutor, as_completed


# ==============================
# 1. CONFIGURE GEMINI
# ==============================
api_key = "AIzaSyDo6e-eteC56M-XxkJ9CG9KZgi5m6oSrLM"
genai.configure(api_key=api_key)
model = genai.GenerativeModel("gemini-2.5-flash")

In [ ]:
# ==============================
# 2. BATCH GENERATOR FUNCTION
# ==============================
def generate_financial_data_batch(batch_size, batch_id):
    prompt = f"""
You are a professional financial data simulator generating
BANK-REALISTIC consumer credit records.

You must simulate real-world banking data with:
- Imperfect human behavior
- Measurement uncertainty
- ONLY 5–7% stochastic noise
- NO explicit or strong data leakage

Generate {batch_size} UNIQUE financial records
for a credit risk dataset (Batch {batch_id}).

========================
STRICT OUTPUT RULES
========================
- Output ONLY valid JSON
- Output must be a JSON array (list of objects)
- No explanations, comments, markdown, or extra text
- No trailing commas
- No placeholder values
- No duplicated records

========================
REAL-WORLD BANKING CONSTRAINTS
========================
- Data must NOT look synthetic or rule-based
- Relationships must be probabilistic, never deterministic
- Only 5–7% of records may contain contradictions or label noise
- Avoid perfect thresholds or linear relationships
- Avoid features that mathematically derive from each other
- Default must NEVER be perfectly predictable from any feature

========================
FEATURE LEAKAGE RULES (CRITICAL)
========================
- Do NOT include any feature that is a direct mathematical
  transformation of another feature
- Do NOT embed default logic into text or categories
- The label must be generated from a latent risk concept,
  NOT from explicit rules

========================
LATENT RISK LOGIC (INTERNAL ONLY)
========================
Default risk should be influenced probabilistically by:
- Income stability (not income alone)
- Credit utilization pressure
- Payment behavior history
- Account tenure
- Employment stability
- Existing debt burden

Then apply:
- Random uncertainty
- Human behavior variation
- 5–7% stochastic overrides (unexpected defaults or recoveries)

========================
CLASS BALANCE REQUIREMENT
========================
- default_risk = 1 for approximately 15–30% of records
- Do NOT cluster defaults into obvious patterns

========================
NUMERIC FIELDS
========================
- age: integer between 21 and 70
- monthly_income: integer between 1500 and 20000
  (null allowed but ≤ 5%)
- credit_utilization_ratio: float between 0.10 and 1.00
- loan_amount: integer between 1000 and 50000
- loan_duration_months: one of [12, 24, 36, 48, 60]
- num_late_payments: integer between 0 and 10
- existing_loans_count: integer between 0 and 5
- account_tenure_years: float between 0 and 20
  (may include decimals, imperfect measurement)

========================
CATEGORICAL FIELDS (RAW, NOT ONE-HOT)
========================
- employment_type:
  "Salaried", "Self-Employed", "Student", "Unemployed"
- education_level:
  "High School", "Diploma", "Bachelor", "Master"
- marital_status:
  "Single", "Married", "Divorced"
- region:
  "Urban", "Suburban", "Rural"

========================
TEXT FIELD (IMPORTANT FOR REALISM)
========================
- customer_financial_statement:
  A single first-person sentence describing the customer's
  current financial situation, stress level, uncertainty,
  confidence, or recent life changes.

Rules for text:
- Do NOT mention default, bankruptcy, or loan approval
- Tone must vary naturally (optimistic, cautious, stressed, neutral)
- Text must NOT explicitly reveal the label

========================
LABEL
========================
- default_risk:
  1 if the customer eventually defaults during the loan period
  0 otherwise

========================
FINAL VALIDATION CHECK
========================
Before outputting:
- No feature perfectly predicts default
- Contradictory but realistic cases exist (≤ 7%)
- Data resembles real consumer banking records
- JSON is syntactically valid
"""


    try:
        response = model.generate_content(prompt)
        text = response.text.strip().replace("```json", "").replace("```", "")
        return json.loads(text)
    except Exception as e:
        print(f"❌ Batch {batch_id} failed:", e)
        return []

In [ ]:
# ==============================
# 3. PARALLEL BATCH PROCESSING
# ==============================
TOTAL_RECORDS = 1800
BATCH_SIZE = 100
MAX_WORKERS = 2

num_batches = (TOTAL_RECORDS + BATCH_SIZE - 1) // BATCH_SIZE
all_records = []

print(f"🚀 Generating {TOTAL_RECORDS} records using Gemini...")
with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
    futures = {
        executor.submit(generate_financial_data_batch, BATCH_SIZE, i + 1): i + 1
        for i in range(num_batches)
    }

    for future in as_completed(futures):
        batch_id = futures[future]
        batch_data = future.result()
        all_records.extend(batch_data)
        print(f"✅ Batch {batch_id} done | Total records: {len(all_records)}")

🚀 Generating 1800 records using Gemini...
❌ Batch 2 failed: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
❌ Batch 1 failed: Expecting value: line 12 column 28 (char 4052)
✅ Batch 2 done | Total records: 0
✅ Batch 1 done | Total records: 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 1084.65ms

❌ Batch 3 failed: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash
Please retry in 59.047415399s.
✅ Batch 3 done | Total records: 0
❌ Batch 4 failed: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
✅ Batch 4 done | Total records: 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 555.23ms

❌ Batch 5 failed: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash
Please retry in 58.478110126s.
✅ Batch 5 done | Total records: 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 555.69ms

❌ Batch 7 failed: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash
Please retry in 57.90914942s.
✅ Batch 7 done | Total records: 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 1114.27ms

❌ Batch 6 failed: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash
Please retry in 57.360132906s.
✅ Batch 6 done | Total records: 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 555.86ms

❌ Batch 8 failed: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash
Please retry in 56.80355055s.
✅ Batch 8 done | Total records: 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 1491.07ms

❌ Batch 9 failed: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash
Please retry in 55.900344452s.
✅ Batch 9 done | Total records: 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 557.83ms

❌ Batch 10 failed: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash
Please retry in 55.306616363s.
✅ Batch 10 done | Total records: 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 1294.49ms

❌ Batch 11 failed: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash
Please retry in 54.611575394s.
✅ Batch 11 done | Total records: 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 556.27ms

❌ Batch 12 failed: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash
Please retry in 54.006060594s.
✅ Batch 12 done | Total records: 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 556.51ms

❌ Batch 14 failed: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash
Please retry in 53.438831529s.
✅ Batch 14 done | Total records: 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 1114.65ms

❌ Batch 13 failed: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash
Please retry in 52.887929245s.
✅ Batch 13 done | Total records: 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 731.93ms

❌ Batch 15 failed: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash
Please retry in 52.183931738s.
✅ Batch 15 done | Total records: 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 1290.65ms

❌ Batch 16 failed: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash
Please retry in 51.592884743s.
✅ Batch 16 done | Total records: 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 1111.97ms

❌ Batch 17 failed: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash
Please retry in 51.036485133s.
✅ Batch 17 done | Total records: 0

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 554.59ms

❌ Batch 18 failed: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash
Please retry in 50.479076672s.
✅ Batch 18 done | Total records: 0

In [ ]:
# ==============================
# 4. CONVERT TO DATAFRAME
# ==============================
df = pd.DataFrame(all_records)

# OPTIONAL: trim excess rows if Gemini over-generates
df = df.iloc[:TOTAL_RECORDS]

print("\n📊 Sample Data:")
print(df.head())

# ==============================
# 5. SAVE TO CSV
# ==============================
output_file = "synthetic_credit_risk_data.csv"
df.to_csv(output_file, index=False)

print(f"\n💾 CSV saved successfully → {output_file}")

📊 Sample Data:
Empty DataFrame
Columns: []
Index: []

💾 CSV saved successfully → synthetic_credit_risk_data.csv

In [ ]:
df.isnull().sum()

Series([], dtype: float64)

In [ ]:
df.shape

(1800, 14)

In [ ]:
df.isnull().sum()

age                               0
employment_type                   0
education_level                   0
marital_status                    0
region                            0
monthly_income                  107
credit_utilization_ratio          0
loan_amount                       0
loan_duration_months              0
num_late_payments                 0
existing_loans_count              0
account_tenure_years              0
customer_financial_statement      0
default_risk                      0
dtype: int64